TrabalhoFinalCinema/Models/Empregados.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabalhoFinalCinema.Models
{
    public class Empregados
    {
        public int Id { get; set; }
        [Required]
        [Display (Name = "Nome")]
        public string Nome { get; set; }
        [Required]
        [Display(Name = "Função")]
        public string Funcao { get; set; }
        [Required]
        [Display(Name = "Salário")]
        public double? Salario { get; set; }
        [Display(Name = "Idade")]
        [Min16Years]
        public int? Idade { get; set; }
        [Required]
        [Display(Name = "Aniversário")]
        public string Aniversario { get; set; }
        [Required]
        public string CPF { get; set; }
    }
}

TrabalhoFinalCinema/Controllers/EmpregadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoFinalCinema.Models;
using TrabalhoFinalCinema.ViewModels;

namespace TrabalhoFinalCinema.Controllers
{
    [Authorize]
    public class EmpregadosController : Controller
    {
        private ApplicationDbContext _context;

        public EmpregadosController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        [Authorize]
        public ActionResult Index()
        {
            var empregados = _context.Empregados.ToList();
            if (User.IsInRole("CanManage"))
                return View(empregados);
            return View("ReadOnlyIndex", empregados);
        }

        public ActionResult Details(int id)
        {
            var empregado = _context.Empregados.SingleOrDefault(e => e.Id == id);
            if (empregado == null)
            {
                return HttpNotFound();
            }

            return View(empregado);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult New()
        {
            var empregado = new Empregados { };

            return View("EmpregadoForm", empregado);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Save(Empregados empregado) // recebemos um cliente
        {
            if (!ModelState.IsValid)
            {
                
                return View("EmpregadoForm", empregado);
            }

            if (empregado.Id == 0)
            {
                // armazena o cliente em memória
                _context.Empregados.Add(empregado);
            }
            else
            {
                var empregadoNoBD = _context.Empregados.Single(c => c.Id == empregado.Id);

                empregadoNoBD.Nome = empregado.Nome;
                empregadoNoBD.Idade = empregado.Idade;
                empregadoNoBD.Aniversario = empregado.Aniversario;
                empregadoNoBD.Funcao = empregado.Funcao;
                empregadoNoBD.Salario = empregado.Salario;
                empregadoNoBD.CPF = empregado.CPF;
            }

            // faz a persistência
            _context.SaveChanges();
            // Voltamos para a lista de clientes
            return RedirectToAction("Index");
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Edit(int id)
        {
            var empregado = _context.Empregados.SingleOrDefault(c => c.Id == id);

            if (empregado == null)
                return HttpNotFound();

            return View("EmpregadoForm", empregado);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Delete(int id)
        {
            var empregados = _context.Empregados.SingleOrDefault(c => c.Id == id);

            if (empregados == null)
                return HttpNotFound();

            _context.Empregados.Remove(empregados);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }

    }
}

TrabalhoFinalCinema/Views/Empregados/Details.cshtml
@model TrabalhoFinalCinema.Models.Empregados
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<ul>
    <li>Idade: @Model.Idade</li>
    <li>Aniversário: @Model.Aniversario</li>
    <li>CPF: @Model.CPF</li>
    <li>Função: @Model.Funcao</li>
    <li>Salario: @Model.Salario</li>
</ul>

TrabalhoFinalCinema/Views/Empregados/EmpregadoForm.cshtml
@model TrabalhoFinalCinema.Models.Empregados
@{
    ViewBag.Title = Model.Id == 0 ? "Novo Empregado" : "Editar Empregado";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Empregados"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Idade)
        @Html.TextBoxFor(m => m.Idade, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Idade)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Funcao)
        @Html.TextBoxFor(m => m.Funcao, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Funcao)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Salario)
        @Html.TextBoxFor(m => m.Salario, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Salario)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Aniversario)
        @Html.TextBoxFor(m => m.Aniversario, "{0: dd/MM/yyyy }", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Aniversario)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CPF)
        @Html.TextBoxFor(m => m.CPF, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CPF)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $.validator.methods.date = function (value, element) {
                Globalize.culture("pt-BR");
                return this.optional(element) || Globalize.parseDate(value) !== null;
            }
        })
    </script>
}

TrabalhoFinalCinema/Views/Empregados/Index.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Empregados>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Empregados</h2>

<p>
    @Html.ActionLink("Novo Empregado", "New", null, new { @class = "btn btn-primary" })
</p>

@if (Model.Any())
{
    <table id="empregados" class="table table-condensed table-hover">
        <thead>
            <tr>
            <th>Nome</th>
            <th>Idade</th>
            <th>Aniversário</th>
            <th>Função</th>
            <th>Salário</th>
            <th>CPF</th>
            
            </tr>
        </thead>
        <tbody>
            @foreach (var empregados in Model)
            {
                <tr>
                    <td>@Html.ActionLink(@empregados.Nome, "Details", new { empregados.Id })</td>
                    <td>@empregados.Idade Anos</td>
                    <td>@empregados.Aniversario</td>
                    <td>@empregados.Funcao</td>
                    <td>R$ @empregados.Salario</td>
                    <td>@empregados.CPF</td>
                    <td align="right"><p>@Html.ActionLink("Editar", "Edit", new { empregados.Id }, new { @class = "btn btn-primary" })</p></td>
                    <td><button data-empregados-id="@empregados.Id" class="btn-link js-delete"> Remover </button></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhum empregado no momento.</p>
}



@section scripts
{
    <script>
        $(document).ready(function () {
            $("#empregados").on("click", ".js-delete",
                function () {
                    var button = $(this);
                    bootbox.confirm("Tem certeza que quer remover este empregado?",
                        function (result) {
                            if (result) {
                                $.ajax({
                                    url: "/empregados/delete/" + button.attr("data-empregados-id"),
                                    method: "GET",
                                    success: function () {
                                        button.parents("tr").remove();
                                    }
                                });
                            }
                        });
                });
        });
    </script>
}

TrabalhoFinalCinema/Views/Empregados/ReadOnlyIndex.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Empregados>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Empregados</h2>

@if (!Model.Any())
{
    <p>Não temos nenhum empregado ainda.</p>
}
else
{
    <table id="empregados" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Empregado</th>
                <th>Função</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var empregados in Model)
            {
                <tr>
                    <td>@empregados.Nome</td>
                    <td>@empregados.Funcao</td>
                </tr>
            }
        </tbody>
    </table>
}