TrabalhoFinalCinema/Models/Comidas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabalhoFinalCinema.Models
{
    public class Comidas
    {
        public int Id { get; set; }
        [Required]
        [Display (Name = "Tipo")]
        public string Tipo { get; set; }
        [Required]
        [Display (Name = "Preço")]
        public double? Preco { get; set; }

    }
}

TrabalhoFinalCinema/Controllers/ComidasController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoFinalCinema.Models;
using TrabalhoFinalCinema.ViewModels;

namespace TrabalhoFinalCinema.Controllers
{
    [Authorize]
    public class ComidasController : Controller
    {
        private ApplicationDbContext _context;

        public ComidasController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose (bool disposing)
        {
            _context.Dispose();
        }

        // GET: Customers
        [Authorize]
        public ActionResult Index()
        {
            var comidas = _context.Comidas.ToList();
            if (User.IsInRole("CanManage"))
                return View(comidas);
            return View("ReadOnlyIndex", comidas);
        }

        public ActionResult Details(int id)
        {
            var comida = _context.Comidas.SingleOrDefault(c => c.Id == id);
            if (comida == null)
            {
                return HttpNotFound();
            }
            return View(comida);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult New()
    {
        var comida = new Comidas();

        return View("ComidaForm", comida);
    }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Save(Comidas comida) // recebemos um cliente
    {
            if (!ModelState.IsValid)
            {
                return View("ComidaForm", comida);
            }

            if (comida.Id == 0)
        {
            // armazena o cliente em memória
            _context.Comidas.Add(comida);
        }
        else
        {
            var comidaNoBD = _context.Comidas.Single(c => c.Id == comida.Id);

                comidaNoBD.Tipo = comida.Tipo;
                comidaNoBD.Preco = comida.Preco;
        }

        // faz a persistência
        _context.SaveChanges();
        // Voltamos para a lista de clientes
        return RedirectToAction("Index");
    }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Edit(int id)
    {
        var comida = _context.Comidas.SingleOrDefault(c => c.Id == id);

        if (comida == null)
            return HttpNotFound();


        return View("ComidaForm", comida);
    }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Delete(int id)
        {
            var comidas = _context.Comidas.SingleOrDefault(c => c.Id == id);

            if (comidas == null)
                return HttpNotFound();

            _context.Comidas.Remove(comidas);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

TrabalhoFinalCinema/Views/Comidas/ComidaForm.cshtml
@model TrabalhoFinalCinema.Models.Comidas
@{
    ViewBag.Title = Model.Id == 0 ? "Nova Comida" : "Editar Comida";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Comidas"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Tipo)
        @Html.TextBoxFor(m => m.Tipo, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Tipo)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Preco)
        @Html.TextBoxFor(m => m.Preco, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Preco)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $.validator.methods.date = function (value, element) {
                Globalize.culture("pt-BR");
                return this.optional(element) || Globalize.parseDate(value) !== null;
            }
        })
    </script>
}

TrabalhoFinalCinema/Views/Comidas/Details.cshtml
@model TrabalhoFinalCinema.Models.Comidas
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Tipo</h2>
<ul>
    <li>Preço: R$@Model.Preco</li>
</ul>

TrabalhoFinalCinema/Views/Comidas/Index.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Comidas>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comidas</h2>

<p>
    @Html.ActionLink("Nova Comida", "New", null, new { @class = "btn btn-primary" })
</p>

@if (Model.Any())
{
    <table id="comida"class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Comida</th>
                <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var comida in Model)
            {
                <tr>
                    <td>@Html.ActionLink(@comida.Tipo, "Details", new { comida.Id })</td>
                    <td>R$ @comida.Preco</td>
                    <td align="right"><p>@Html.ActionLink("Editar", "Edit", new { comida.Id }, new { @class = "btn btn-primary"})</p></td>
                    <td><button data-comida-id="@comida.Id" class="btn-link js-delete"> Remover </button></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhuma comida disponível no momento.</p>
}


@section scripts
{
    <script>
        $(document).ready(function () {
            $("#comida").on("click", ".js-delete",
                function () {
                    var button = $(this);
                    bootbox.confirm("Tem certeza que quer remover esta comida?",
                        function (result) {
                            if (result) {
                                $.ajax({
                                    url: "/comidas/delete/" + button.attr("data-comida-id"),
                                    method: "GET",
                                    success: function () {
                                        button.parents("tr").remove();
                                    }
                                });
                            }
                        });
                });
        });
    </script>
}

TrabalhoFinalCinema/Views/Comidas/ReadOnlyIndex.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Comidas>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comidas</h2>

@if (!Model.Any())
{
    <p>Não temos nenhuma comida ainda.</p>
}
else
{
    <table id="comida" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Comida</th>
                <th>Preço</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var comida in Model)
            {
                <tr>
                    <td>@comida.Tipo</td>
                    <td>R$ @comida.Preco</td>
                </tr>
            }
        </tbody>
    </table>
}