TrabalhoFinalCinema/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TrabalhoFinalCinema.Models
{
    public class Filme
    {
    }
}

TrabalhoFinalCinema/Models/Filmes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabalhoFinalCinema.Models
{
    public class Filmes
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string Nome { get; set; }
        [Required]
        [Display(Name = "Gênero")]
        public string Genero { get; set; }
        [Required]
        [Display(Name = "Idade Mínima")]
        public string IdadeMinima { get; set; }
        [Required]
        [Display(Name = "Horário")]
        public string Horario { get; set; }
        [Required]
        [Display(Name = "Linguagem")]
        public string Linguagem { get; set; }
        [Required]
        [Display(Name = "Duração")]
        public int? Duracao { get; set; }
    }

}

TrabalhoFinalCinema/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoFinalCinema.Models;
using TrabalhoFinalCinema.ViewModels;

namespace TrabalhoFinalCinema.Controllers
{
    [Authorize]
    public class FilmesController : Controller
    {
        private ApplicationDbContext _context;
        public FilmesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        [Authorize]
        public ActionResult Index()
        {
            var filmes = _context.Filmes.ToList();
            if (User.IsInRole("CanManage"))
                return View(filmes);
            return View("ReadOnlyIndex", filmes);
        }

        public ActionResult Details(int id)
        {
            var filme = _context.Filmes.SingleOrDefault(f => f.Id == id);
            if (filme == null)
            {
                return HttpNotFound();
            }

            return View(filme);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult New()
    {
        var filme = new Filmes{ };

        return View("FilmeForm", filme);
    }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Save(Filmes filme) // recebemos um cliente
    {
            if (!ModelState.IsValid)
            {
                var viewModel = new FilmesIndexViewModel{ };

                return View("FilmeForm", viewModel);
            }

            if (filme.Id == 0)
        {
            // armazena o cliente em memória
            _context.Filmes.Add(filme);
        }
        else
        {
            var filmeNoBD = _context.Filmes.Single(c => c.Id == filme.Id);

            filmeNoBD.Nome = filme.Nome;
            filmeNoBD.Genero = filme.Genero;
            filmeNoBD.IdadeMinima = filme.IdadeMinima;
            filmeNoBD.Horario = filme.Horario;
            filmeNoBD.Linguagem = filme.Linguagem;
            filmeNoBD.Duracao = filme.Duracao;
        }

        // faz a persistência
        _context.SaveChanges();
        // Voltamos para a lista de clientes
        return RedirectToAction("Index");
    }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Edit(int id)
    {
        var filme = _context.Filmes.SingleOrDefault(f => f.Id == id);

        if (filme == null)
            return HttpNotFound();

        return View("FilmeForm", filme);
    }


        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Delete(int id)
        {
            var filmes = _context.Filmes.SingleOrDefault(c => c.Id == id);

            if (filmes == null)
                return HttpNotFound();

            _context.Filmes.Remove(filmes);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

TrabalhoFinalCinema/Views/Filmes/Details.cshtml
@model TrabalhoFinalCinema.Models.Filmes
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<ul>
    <li>Idade Mínima: @Model.IdadeMinima</li>
    <li>Gênero: @Model.Genero</li>
    <li>Duração: @Model.Duracao min</li>
    <li>Horários: @Model.Horario</li>
    <li>Linguagem: @Model.Linguagem</li>
</ul>

TrabalhoFinalCinema/Views/Filmes/FilmeForm.cshtml
@model TrabalhoFinalCinema.Models.Filmes
@{
    ViewBag.Title = Model.Id == 0 ? "Novo Filme" : "Editar Filme";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Filmes"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Genero)
        @Html.TextBoxFor(m => m.Genero, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Genero)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.IdadeMinima)
        @Html.TextBoxFor(m => m.IdadeMinima, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.IdadeMinima)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Horario)
        @Html.TextBoxFor(m => m.Horario, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Horario)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Linguagem)
        @Html.TextBoxFor(m => m.Linguagem, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Linguagem)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Duracao)
        @Html.TextBoxFor(m => m.Duracao, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Duracao)
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $.validator.methods.date = function (value, element) {
                Globalize.culture("pt-BR");
                return this.optional(element) || Globalize.parseDate(value) !== null;
            }
        })
    </script>
}

TrabalhoFinalCinema/Views/Filmes/Index.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Filmes>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Filmes</h2>

<p>
    @Html.ActionLink("Novo Filme", "New", null, new { @class = "btn btn-primary" })
</p>

@if (Model.Any())
{
    <table id="filme" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Filme</th>
                <th>Gênero</th>
                <th>Horários</th>
                <th>Idade Mínima</th>
                <th>Linguagem</th>
                <th>Duração</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var filme in Model)
            {
                <tr>
                    <td>@Html.ActionLink(@filme.Nome, "Details", new { filme.Id })</td>
                    <td>@filme.Genero</td>
                    <td>@filme.Horario</td>
                    <td>@filme.IdadeMinima Anos</td>
                    <td>@filme.Linguagem</td>
                    <td>@filme.Duracao min</td>
                    <td align="right"><p>@Html.ActionLink("Editar","Edit", new { filme.Id }, new { @class = "btn btn-primary" })</p></td>
                    <td><button data-filme-id="@filme.Id" class="btn-link js-delete"> Remover </button></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhum filme disponível no momento.</p>
}


@section scripts
{
    <script>
        $(document).ready(function () {
            $("#filme").on("click", ".js-delete",
                function () {
                    var button = $(this);
                    bootbox.confirm("Tem certeza que quer remover este filme?",
                        function (result) {
                            if (result) {
                                $.ajax({
                                    url: "/filmes/delete/" + button.attr("data-filme-id"),
                                    method: "GET",
                                    success: function () {
                                        button.parents("tr").remove();
                                    }
                                });
                            }
                        });
                });
        });
    </script>
}

TrabalhoFinalCinema/Views/Filmes/ReadOnlyIndex.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Filmes>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Filmes</h2>

@if (!Model.Any())
{
    <p>Não temos nenhum filme ainda.</p>
}
else
{
    <table id="filme" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Filme</th>
                <th>Gênero</th>
                <th>Horários</th>
                <th>Idade Mínima</th>
                <th>Linguagem</th>
                <th>Duração</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var filme in Model)
            {
                <tr>
                    <td>@filme.Nome</td>
                    <td>@filme.Genero</td>
                    <td>@filme.Horario</td>
                    <td>@filme.IdadeMinima Anos</td>
                    <td>@filme.Linguagem</td>
                    <td>@filme.Duracao min</td>
                </tr>
            }
        </tbody>
    </table>
}