TrabalhoFinalCinema/Models/Salas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrabalhoFinalCinema.Models
{
    public class Salas
    {
        [Required]
        [Display (Name = "Nome")]
        public string Nome { get; set; }
        public int Id { get; set; }
        [Required]
        [Display(Name = "Capacidade de Pessoas")]
        public int? CapacidadePessoas { get; set; }
        [Required]
        [Display(Name = "3D")]
        public bool TresD { get; set;}
    }
}

TrabalhoFinalCinema/Controllers/SalasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabalhoFinalCinema.Models;
using TrabalhoFinalCinema.ViewModels;

namespace TrabalhoFinalCinema.Controllers
{
    [Authorize]
    public class SalasController : Controller
    {
        private ApplicationDbContext _context;

        public SalasController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Customers
        [Authorize]
        public ActionResult Index()
        {
            var salas = _context.Salas.ToList();
            if (User.IsInRole("CanManage"))
                return View(salas);
            return View("ReadOnlyIndex", salas);
        }

        public ActionResult Details(int id)
        {
            var sala = _context.Salas.SingleOrDefault(s => s.Id == id);
            if (sala == null)
            {
                return HttpNotFound();
            }

            return View(sala);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult New()
        {
            var sala = new Salas();

            return View("SalaForm", sala);
        }

        [HttpPost] // só será acessada com POST
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Save(Salas sala) // recebemos um cliente
    {
            if (!ModelState.IsValid)
            {
                var viewModel = new SalasIndexViewModel { };
                return View("SalaForm", sala);
            }

            if (sala.Id == 0)
        {
            // armazena o cliente em memória
            _context.Salas.Add(sala);
        }
        else
        {
            var salaNoBD = _context.Salas.Single(c => c.Id == sala.Id);

            salaNoBD.Nome = sala.Nome;
            salaNoBD.CapacidadePessoas = sala.CapacidadePessoas;
            salaNoBD.TresD = sala.TresD;
        }

        // faz a persistência
        _context.SaveChanges();
        // Voltamos para a lista de clientes
        return RedirectToAction("Index");
    }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Edit(int id)
        {
            var sala = _context.Salas.SingleOrDefault(c => c.Id == id);

            if (sala == null)
                return HttpNotFound();

            return View("SalaForm", sala);
        }

        [Authorize(Roles = RoleName.CanManage)]
        public ActionResult Delete(int id)
        {
            var salas = _context.Salas.SingleOrDefault(c => c.Id == id);

            if (salas == null)
                return HttpNotFound();

            _context.Salas.Remove(salas);
            _context.SaveChanges();

            return new HttpStatusCodeResult(200);
        }
    }
}

TrabalhoFinalCinema/Views/Salas/Details.cshtml
@model TrabalhoFinalCinema.Models.Salas
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Nome</h2>
<ul>
    <li>Capacidade de Pessoas: @Model.CapacidadePessoas</li>
    <li>Possui 3D: @Model.TresD</li>
</ul>

TrabalhoFinalCinema/Views/Salas/Index.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Salas>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Salas</h2>

<p>
    @Html.ActionLink("Nova Sala", "New", null, new { @class = "btn btn-primary" })
</p>

@if (Model.Any())
{
    <table id="sala" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Sala</th>
                <th>Capacidade de Pessoas</th>
                <th>3D</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sala in Model)
            {
                <tr>
                    <td>@Html.ActionLink(@sala.Nome, "Details", new { sala.Id })</td>
                    <td>@sala.CapacidadePessoas</td>
                    <td>@sala.TresD</td>
                    <td align="right"><p>@Html.ActionLink("Editar", "Edit", new { sala.Id }, new { @class = "btn btn-primary" })</p></td>
                    <td><button data-sala-id="@sala.Id" class="btn-link js-delete"> Remover </button></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhuma sala disponível no momento.</p>
}


@section scripts
{
    <script>
        $(document).ready(function () {
            $("#sala").on("click", ".js-delete",
                function () {
                    var button = $(this);
                    bootbox.confirm("Tem certeza que quer remover esta Sala?",
                        function (result) {
                            if (result) {
                                $.ajax({
                                    url: "/salas/delete/" + button.attr("data-sala-id"),
                                    method: "GET",
                                    success: function () {
                                        button.parents("tr").remove();
                                    }
                                });
                            }
                        });
                });
        });
    </script>
}

TrabalhoFinalCinema/Views/Salas/ReadOnlyIndex.cshtml
@model IEnumerable<TrabalhoFinalCinema.Models.Salas>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Salas</h2>

@if (!Model.Any())
{
    <p>Não temos nenhuma sala ainda.</p>
}
else
{
    <table id="sala" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Sala</th>
                <th>Capacidade de Pessoas</th>
                <th>3D</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sala in Model)
            {
                <tr>
                    <td>@sala.Nome</td>
                    <td>@sala.CapacidadePessoas</td>
                    <td>@sala.TresD</td>
                </tr>
            }
        </tbody>
    </table>
}

TrabalhoFinalCinema/Views/Salas/SalaForm.cshtml
@model TrabalhoFinalCinema.Models.Salas
@{
    ViewBag.Title = Model.Id == 0 ? "Nova Sala" : "Editar Sala";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Salas"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CapacidadePessoas)
        @Html.TextBoxFor(m => m.CapacidadePessoas, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CapacidadePessoas)
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.TresD) Sala 3D
        </label>
    </div>
    
    <button type="submit" class="btn btn-primary">Salvar</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $.validator.methods.date = function (value, element) {
                Globalize.culture("pt-BR");
                return this.optional(element) || Globalize.parseDate(value) !== null;
            }
        })
    </script>
}